eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 8901

spring:
  datasource:
    name: common
    url: jdbc:mysql://localhost:3306/common?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 15
      maximum-pool-size: 15


