spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: service-organization
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mapper:
  mappers: com.paladin.framework.mybatis.CustomMapper
  enumAsSimpleType: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000

paladin:
  shiro:
    tokenField: token
    redisEnabled: true