eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 8901

spring:
  datasource:
    name: common
    url: jdbc:mysql://172.16.16.120:3306/common?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: netin
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 15
      maximum-pool-size: 15
  redis:
    database: 0
    host: 172.16.16.120
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 500


jwt:
  key: iljOQvU3MdAu99fJEGQn0yi5VUNttMMD0EKcwtqbE4EDpBqYWSgsgs5T9V9fVgBDh3VDpCaYEJdewLG4f8wxEcLcNF7sSIWYSjjF01ObeFjxTo4frSfy2aliJABV2
  issuer: organization
  expire-millisecond: 1800000