spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: service-organization
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mapper:
  mappers: com.paladin.framework.mybatis.CustomMapper