server:
  port: 8900

spring:
  cloud:
    nacos:
      server-addr: 172.16.16.120:8848
    gateway:
      locator:
        enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:63342"
            allowedMethods:
              - GET
              - POST
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      routes:
        - predicates:
            - Path=/organization/authenticate/**
          uri: lb://service-organization
        - id: organization-api
          predicates:
            - Path=/organization/v2/api-docs
          uri: lb://service-organization
          filters:
            - StripPrefix=1
        - predicates:
            - Path=/organization/**
          uri: lb://service-organization
          filters:
            - name: Auth
              args:
                jwtBase64Key: deDFCOSOeuWNmkTqDLkeFRYe4Eunimz4cescnhGA3J8=


paladin:
  cors-enabled: true