spring:
  profiles:
    active: @spring.profiles.active@
  application:
      name: service-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
