eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 8900

spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/organization/authenticate
          uri: lb://service-organization
        - predicates:
            - Path=/organization/**
          uri: lb://service-organization
          filters:
            - name: Auth
              args:
                jwtBase64Key: iljOQvU3MdAu99fJEGQn0yi5VUNttMMD0EKcwtqbE4EDpBqYWSgsgs5T9V9fVgBDh3VDpCaYEJdewLG4f8wxEcLcNF7sSIWYSjjF01ObeFjxTo4frSfy2aliJABV2
        - predicates:
            - Path=/supervise/**
          uri: lb://service-supervise
          filters:
            - name: Auth
              args:
                jwtBase64Key: iljOQvU3MdAu99fJEGQn0yi5VUNttMMD0EKcwtqbE4EDpBqYWSgsgs5T9V9fVgBDh3VDpCaYEJdewLG4f8wxEcLcNF7sSIWYSjjF01ObeFjxTo4frSfy2aliJABV2

