eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 8900

zuul:
  routes:
    organization:
      path: /organization/**
      serviceId: service-organization
      strip-prefix: false
    supervise:
      path: /supervise/**
      serviceId: service-supervise
      strip-prefix: false

